[DEFAULT]

username=Administrator
groups=Administrators

inject_user_password=true
first_logon_behaviour=no
rename_admin_user=false

verbose=true
debug=false

log_dir=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log\
log_file=cloudbase-init.log

default_log_levels=comtypes=INFO,suds=INFO,iso8601=WARN,requests=WARN

logging_serial_port_settings=

mtu_use_dhcp_config=true
ntp_use_dhcp_config=true

local_scripts_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\LocalScripts\

metadata_services=cloudbaseinit.metadata.services.configdrive.ConfigDriveService

allow_reboot=true
stop_service_on_exit=false
check_latest_version=false

[config_drive]

raw_hdd=false
cdrom=true
vfat=false

types=iso
locations=cdrom